name: Deploy React to EC2

on:
  push:
    branches: [ "main" ]   # change if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: TEST-GITHUB-ACTION

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > private.pem
        chmod 600 private.pem

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i private.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ${{ secrets.APP_PATH }}
          git fetch --all
          git reset --hard origin/main
          npm install --legacy-peer-deps
          npm run build
          pm2 restart calculator || pm2 start npm --name "calculator" -- start
        EOF
